packages:
  - "."
  - "packages/*"
  - "providers/*"

overrides:
  "@earendil-works/pi-coding-agent@0.80.3>@earendil-works/pi-agent-core": 0.80.3
  "@earendil-works/pi-coding-agent@0.80.3>@earendil-works/pi-ai": 0.80.3
  "@earendil-works/pi-coding-agent@0.80.3>@earendil-works/pi-tui": 0.80.3

allowBuilds:
  "@google/genai": false
  esbuild: false
  protobufjs: false
