import { strict as assert } from "node:assert";
import { readFile } from "node:fs/promises";
import { defaultConfig, normalizeConfig } from "../config.js";
import { GLANCE_THEMES } from "../themes.js";

const readme = await readFile("README.md", "utf8");
const readmeZh = await readFile("README.zh-CN.md", "utf8");

function assertReadmeIncludes(fragment: string, message: string): void {
	assert.ok(readme.includes(fragment), message);
}

function assertReadmeExcludes(fragment: string, message: string): void {
	assert.equal(readme.includes(fragment), false, message);
}

assertReadmeIncludes("maintained fork", "README should identify this package as a maintained fork");
assertReadmeIncludes("pi install npm:@zhcsyncer/pi-glance", "README should install the scoped fork package");
assertReadmeIncludes("Pi 0.80.4 or newer", "README should document the agent_settled-compatible Pi baseline");
assertReadmeIncludes("public `agent_settled` lifecycle event", "README should explain the minimum Pi version");
assertReadmeIncludes("Other extensions' `ctx.ui.setStatus()` values remain visible", "README should document preserved extension statuses");
assertReadmeIncludes("**Bottom details**", "README should document the remaining bottom-details settings category");
assertReadmeIncludes("`Progress bar`", "README should document the bottom-right context progress toggle");
assertReadmeIncludes("standalone `track` or a progress-aware `border`", "README should document both context progress styles");
assertReadmeIncludes("unused cells stay light `─`, used cells become heavy `━`, and `╼` joins them", "README should document the border progress glyph encoding");
assertReadmeIncludes("The percentage keeps normal text color", "README should document the quieter percentage hierarchy");
assertReadmeIncludes("bottom progress omits the context icon", "README should document the icon-free bottom progress design");
assertReadmeIncludes("Nerd Font text modes still use `󰍛`", "README should document where the Nerd Font context icon remains visible");
assertReadmeIncludes("Nerd Font mode shows the highlighted `󰁄 auto` marker", "README should document the labeled auto-compaction Nerd Font marker");
assertReadmeIncludes("all `remaining` bottom-border space", "README should document the remaining-width mode");
assertReadmeIncludes("below 70%", "README should document the normal context risk range");
assertReadmeIncludes("at 85% or higher", "README should document the context error threshold");
assertReadmeExcludes('"showDefaultStatus"', "README should not document a removed Pi status-row switch");
assertReadmeExcludes('"enabled": true,\n    "showSession"', "README should not document the removed bottom-details master and session switches");
assert.equal("footer" in defaultConfig(), false, "README footer behavior should stay aligned with config removal");
assert.deepEqual(defaultConfig().bottomDetails, { showAutoCompact: true }, "README bottom-details JSON should stay aligned with defaultConfig");
assert.deepEqual(defaultConfig().context, { text: "percent+tokens", progress: false, progressStyle: "border", progressWidth: "third" }, "README context progress defaults should stay aligned with defaultConfig");
assert.ok(readmeZh.includes("pi install npm:@zhcsyncer/pi-glance"), "Chinese README should document scoped install");
assert.ok(readmeZh.includes("Footer 组合"), "Chinese README should document footer composition");
assert.ok(readmeZh.includes("右下角详情"), "Chinese README should document bottom-right details");
assert.ok(readmeZh.includes("Progress bar"), "Chinese README should document context progress mode");
assert.ok(readmeZh.includes("未用部分保持细线 `─`，已用部分变为粗线 `━`"), "Chinese README should document border progress glyphs");
assert.ok(readmeZh.includes("70%（含）到 85%（不含）使用 warning，85% 及以上使用 error"), "Chinese README should document fixed context risk thresholds");
assertReadmeIncludes("Icons default to `plain`", "README should state that icons default to plain");
assertReadmeIncludes("`nerd` icons are opt-in", "README should state that nerd icons are opt-in");
assertReadmeIncludes("/glance` → **General** → `Icons`", "README should point users to /glance General Icons");
assertReadmeIncludes("Nerd icons need a Nerd Font or Symbols Nerd Font fallback", "README should explain Nerd Font fallback requirement");
assertReadmeIncludes("If icons look like boxes, choose `plain`", "README should explain the plain fallback when icons render as boxes");
assertReadmeIncludes("does not auto-detect, install, or bundle terminal fonts", "README should avoid implying font detection/install/bundling");
assertReadmeIncludes("Claude-inspired working indicator", "README should describe the Claude-inspired working indicator");
assertReadmeIncludes("not an official Anthropic component", "README should rule out official Anthropic provenance");
assertReadmeIncludes("does not change the Agent, prompts, models, tools, messages, or session behavior", "README should document display-only behavior");
assertReadmeIncludes("**Working indicator** directly in the first-level menu", "README should document the first-level working-indicator entry");
assertReadmeIncludes("one `Enabled: on/off` switch", "README should document the single working-indicator toggle");
assertReadmeIncludes("each first-level item remembers its last selected child row", "README should document parent and child cursor preservation");
assertReadmeIncludes("Pi's public `estimateTokens()`", "README should document Pi's public partial-token estimator");
assertReadmeIncludes("Completed assistant messages use provider-reported `usage.output`", "README should document finalized working-output accounting");
assertReadmeIncludes("without double counting", "README should document estimate replacement rather than addition");
assertReadmeIncludes("existing 120ms working-row ticker", "README should document single-ticker streaming coalescing");
assertReadmeIncludes("instead of showing `↓ ~0 tokens`", "README should document empty-partial suppression");
assertReadmeIncludes("Top-border Tokens — current session cumulative usage", "README should distinguish session usage from working output");
assertReadmeIncludes("Context — current context-window occupancy", "README should distinguish context occupancy from output counters");
assertReadmeIncludes("Elapsed time stays compact and human-readable", "README should document human-readable working elapsed time");
assertReadmeIncludes("uses the theme warning color at five minutes or later", "README should document long-cycle elapsed emphasis");
assertReadmeIncludes("it is retained ahead of cycle tokens", "README should document warning elapsed narrow-width priority");
assertReadmeIncludes("global singleton with no owner stack", "README should document working-row ownership limits");
assertReadmeIncludes("schema version 13", "README should document config schema 13");
assert.deepEqual(defaultConfig().workingIndicator, { enabled: true }, "README working default should stay aligned with config");
assert.ok(readmeZh.includes("不是 Anthropic 官方组件"), "Chinese README should rule out official Anthropic provenance");
assert.ok(readmeZh.includes("一级菜单直接显示 **Working indicator**"), "Chinese README should document the first-level working entry");
assert.ok(readmeZh.includes("只有一个 `Enabled: on/off` 开关"), "Chinese README should document the single working switch");
assert.ok(readmeZh.includes("记住上次选中的子项"), "Chinese README should document parent and child cursor preservation");
assert.ok(readmeZh.includes("当前高层 cycle output"), "Chinese README should document working-token scope");
assert.ok(readmeZh.includes("现有 120ms working-row ticker 合并"), "Chinese README should document single-ticker streaming coalescing");
assert.ok(readmeZh.includes("不显示 `↓ ~0 tokens`"), "Chinese README should document empty-partial suppression");
assert.ok(readmeZh.includes("当前 session 累计 usage"), "Chinese README should document session-token scope");
assert.ok(readmeZh.includes("当前 context window 占用"), "Chinese README should document context scope");
assert.ok(readmeZh.includes("耗时保持紧凑且易读"), "Chinese README should document human-readable working elapsed time");
assert.ok(readmeZh.includes("五分钟及以上使用主题 warning 色"), "Chinese README should document long-cycle elapsed emphasis");
assert.ok(readmeZh.includes("优先于 cycle token 保留"), "Chinese README should document warning elapsed narrow-width priority");
assert.ok(readmeZh.includes("当前 schema 为版本 13"), "Chinese README should document schema 13");

assert.equal(GLANCE_THEMES.length, 22, "README theme copy should describe the curated 22-theme collection");
assertReadmeIncludes("22 built-in Glance palettes", "README should describe the curated 22-theme fallback collection");
assertReadmeIncludes("`Color source` → `Follow Pi`", "README should document the new-install Follow Pi setting");
assertReadmeIncludes("`Light palette` and `Dark palette`", "README should document the split fallback palette rows");
assertReadmeIncludes("Both browsers contain all 22 palettes", "README should state both palette slots can choose all built-ins");
assertReadmeIncludes("matching tone listed first", "README should document slot-aware preferred ordering without filtering");
assertReadmeIncludes("pi-glance is not a Pi theme manager", "README should avoid implying Pi theme management");
assertReadmeIncludes("never enumerates, switches, or installs Pi themes", "README should explicitly rule out Pi theme enumeration/switching");
assertReadmeIncludes("maps the frame, text, status, warning, error, title, detail, and working-indicator roles to Pi semantic theme tokens", "README should document Follow Pi semantic styling including the working row");
assertReadmeIncludes('"colorSource": "pi"', "README should document the new-install color source default");
assertReadmeIncludes('"theme": {\n    "light": "light",\n    "dark": "dark"\n  }', "README should document the fallback theme pair default");
assert.equal(defaultConfig().colorSource, "pi", "README color-source copy should stay aligned with defaultConfig");
assert.equal("startupHeader" in defaultConfig(), false, "README/config contract should not expose a custom Header setting");
assert.deepEqual(defaultConfig().theme, { light: "light", dark: "dark" }, "README fallback theme copy should stay aligned with defaultConfig");
assert.deepEqual(normalizeConfig({ version: 10 }).colorSource, "glance", "README legacy color-source migration should stay aligned with config normalization");
assert.deepEqual(normalizeConfig({ theme: "tokyo-night" }).theme, { light: "tokyo-night", dark: "tokyo-night" }, "README old string theme migration should stay aligned with config normalization");
assertReadmeIncludes("pi-glance never replaces Pi's native Header or resource area", "README should document native Header ownership");
assertReadmeIncludes("focused frame uses the selected Color source border and does not change with thinking level", "README should document stable normal frame coloring");
assertReadmeIncludes("Bash is the only dynamic exception", "README should document the Bash-only border exception");
assertReadmeIncludes("Glance palette` uses the selected light/dark built-in pair for the frame, segments, context progress, and working indicator", "README should document palette-wide styling including the working row");
assertReadmeIncludes("Filled and unused border colors come from the selected Color source", "README should document context progress source consistency");
assertReadmeIncludes("the dynamic status gets width first", "README should document status-first narrow top-border behavior");
assertReadmeIncludes("the workspace title shortens into the remaining space, then disappears", "README should document workspace-title fallback behavior");
assertReadmeIncludes("segment order configured in `/glance` is also its priority order", "README should document configured segment priority");
assertReadmeIncludes("Bash labels (`Bash` / `Bash · no context`) and the editor's `↑ N more` scroll indicator are higher-priority interaction cues", "README should preserve Bash and scroll-indicator priority");
assertReadmeIncludes("Long input height, internal scrolling", "README should document inherited Pi editor behavior");
assertReadmeIncludes("Context/Skills/Prompts/Extensions keep Pi's native compact/expanded hierarchy", "README should document preserved native resource ownership");
assertReadmeIncludes("grouped by project/user/path", "README should document native Extensions scope grouping");
assertReadmeIncludes("`npm:`/`git:` package sources and local file paths", "README should document native Extensions installation-source detail");
assert.ok(readmeZh.includes('"colorSource": "pi"'), "Chinese README should document Follow Pi defaults");
assert.ok(readmeZh.includes("pi-glance 不替换 Pi 原生 Header 或资源区"), "Chinese README should document native Header ownership");
assert.ok(readmeZh.includes("动态状态优先获得宽度"), "Chinese README should document status-first narrow top-border behavior");
assert.ok(readmeZh.includes("工作区标题先在剩余空间中缩短，空间太小时再隐藏"), "Chinese README should document workspace-title fallback behavior");
assert.ok(readmeZh.includes("segment 顺序作为优先级"), "Chinese README should document configured segment priority");
assert.ok(readmeZh.includes("属于更高优先级的交互提示"), "Chinese README should preserve Bash and scroll-indicator priority");
assert.ok(readmeZh.includes("不再跟随 thinking level"), "Chinese README should document stable normal frame coloring");
assert.ok(readmeZh.includes("Context、Skills、Prompts、Extensions"), "Chinese README should document preserved Pi resource summaries");
assert.ok(readmeZh.includes("project/user/path"), "Chinese README should document native Extensions scope grouping");
assert.ok(readmeZh.includes("`npm:`/`git:` 包来源和本地文件路径"), "Chinese README should document native Extensions installation sources");

console.log("✓ README copy checks passed");
